import type { Metadata } from "next";
import HeaderContainer from "@/container/HeaderContainer";
import { getDictionary } from "./dictionaries";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: "en" | "ar" };
}>) {
  const dictionaries = await getDictionary(params.lang);
  return (
    <div dir={params.lang === "ar" ? "rtl" : "ltr"}>
      <HeaderContainer
        headers={dictionaries.header}
        headerButtonText={dictionaries.headerButton}
      />
      {children}
    </div>
  );
}
